# Generated by CodiumAI

from tpscanner.core.scanner import Scanner


class TestRemoveUnavailableItems:
    # Removes all unavailable items from the individual deals.
    def test_remove_all_unavailable_items(self):
        level = "Scanner Level 1"
        urls = ["https://www.example.com/item1", "https://www.example.com/item2"]
        quantities = [1, 2]
        wait = 5
        headless = True
        console_out = True
        excel_out = False

        scanner = Scanner(
            level, urls, quantities, wait, headless, console_out, excel_out
        )
        scanner.individual_deals = {
            "Item 1": [
                {"availability": True, "seller": "Seller A"},
                {"availability": False, "seller": "Seller B"},
                {"availability": True, "seller": "Seller C"},
            ],
            "Item 2": [
                {"availability": False, "seller": "Seller A"},
                {"availability": True, "seller": "Seller B"},
                {"availability": False, "seller": "Seller C"},
            ],
        }

        removed_items_count = scanner.remove_unavailable_items()

        assert removed_items_count == 3
        assert scanner.individual_deals == {
            "Item 1": [
                {"availability": True, "seller": "Seller A"},
                {"availability": True, "seller": "Seller C"},
            ],
            "Item 2": [
                {"availability": True, "seller": "Seller B"},
            ],
        }

    # Removes no items since they are all available.

    def test_remove_no_items(self):
        level = "Scanner Level 1"
        urls = ["https://www.example.com/item1", "https://www.example.com/item2"]
        quantities = [1, 2]
        wait = 5
        headless = True
        console_out = True
        excel_out = False

        scanner = Scanner(
            level, urls, quantities, wait, headless, console_out, excel_out
        )
        scanner.individual_deals = {
            "Item 1": [
                {"availability": True, "seller": "Seller A"},
                {"availability": True, "seller": "Seller B"},
                {"availability": True, "seller": "Seller C"},
            ],
            "Item 2": [
                {"availability": True, "seller": "Seller A"},
                {"availability": True, "seller": "Seller B"},
                {"availability": True, "seller": "Seller C"},
            ],
        }

        removed_items_count = scanner.remove_unavailable_items()

        assert removed_items_count == 0
        assert scanner.individual_deals == {
            "Item 1": [
                {"availability": True, "seller": "Seller A"},
                {"availability": True, "seller": "Seller B"},
                {"availability": True, "seller": "Seller C"},
            ],
            "Item 2": [
                {"availability": True, "seller": "Seller A"},
                {"availability": True, "seller": "Seller B"},
                {"availability": True, "seller": "Seller C"},
            ],
        }
